MyFirstMVCWebApp/Models/Domacin.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


    public class Domacin : Korisnik
    {
        Dictionary<int, Apartman> apartmaniZaIzdavanje = new Dictionary<int, Apartman>();

        public Domacin(string KorisnickoIme, string Lozinka, string Ime, string Prezime, string Pol)
        {
            base.Ime = Ime;
            base.KorisnickoIme = KorisnickoIme;
            base.Lozinka = Lozinka;
            base.Prezime = Prezime;
            if (Pol == Enumeracije.Pol.MUSKO.ToString())
            {
                base.Pol = Enumeracije.Pol.MUSKO;
            }
            else
                base.Pol = Enumeracije.Pol.ZENSKO;
            base.Uloga = Enumeracije.Uloga.DOMACIN;
        }

    public Dictionary<int, Apartman> ApartmaniZaIzdavanje { get => apartmaniZaIzdavanje; set => apartmaniZaIzdavanje = value; }
}

MyFirstMVCWebApp/Controllers/DomacinController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyFirstMVCWebApp.Controllers
{
    public class DomacinController : Controller
    {
        // GET: Domacin
        
        public ActionResult Index(FormCollection form,string STATUS,string TIP, string Grad, string CenaOd, string CenaDo, string BrojOsoba, string BrojSoba)
        {
            HttpCookie cookie = Request.Cookies["Korisnik"];
            var domacin = Domacini.domacini[cookie.Value];

            List<Apartman> apartmani = new List<Apartman>();
            foreach (var apart in Domacini.domacini[domacin.KorisnickoIme].ApartmaniZaIzdavanje.Values)
            {
                if (apart.Obrisan == false)
                {
                    apartmani.Add(apart);
                }
            }

            if (Request["dugme"] == "sortiraj")
            {
                apartmani = sortiranje(apartmani, Request["SORTIRANJE"]);
            }
            else if (Request["dugme"] == "Primeni filter")
            {
                if (!string.IsNullOrEmpty(form["Sadrzaji"]))
                {
                    apartmani = filtrirajPoSadrzaji(apartmani, form["Sadrzaji"]);
                }
                if (STATUS != null && STATUS != "SVI")
                {
                    Enumeracije.StatusApartmana status;
                    if (STATUS == "AKTIVAN")
                    {
                        status = Enumeracije.StatusApartmana.AKTIVAN;
                    }
                    else
                    {
                        status = Enumeracije.StatusApartmana.NEAKTIVAN;
                    }
                    List<Apartman> apartmaniPom = new List<Apartman>();
                    foreach (var apart in apartmani)
                    {
                        if (apart.StatusApartmana == status)
                        {
                            apartmaniPom.Add(apart);
                        }
                    }
                    apartmani = apartmaniPom;
                }
                if (TIP != null && TIP != "SVI")
                {
                    Enumeracije.TipApart tip;
                    if (TIP == "CEO_APART")
                    {
                        tip = Enumeracije.TipApart.CEO_APART;
                    }
                    else
                    {
                        tip = Enumeracije.TipApart.SOBA;
                    }
                    List<Apartman> apartmaniPom = new List<Apartman>();
                    foreach (var apart in apartmani)
                    {
                        if (apart.TipApartmana == tip)
                        {
                            apartmaniPom.Add(apart);
                        }
                    }
                    apartmani = apartmaniPom;
                }
            }
            else if (Request["dugme"] == "Pretrazi")
            {
                apartmani = pretraga(apartmani, Grad, BrojOsoba, BrojSoba, CenaOd, CenaDo);
            }

            ViewBag.ListaSadrzaja = GetSadrzaj(null);

            return View(apartmani);

        }

        public ActionResult PrikazProfila()
        {
            HttpCookie cookie = Request.Cookies["Korisnik"];
            var domacin = Domacini.domacini[cookie.Value];
            return View(domacin);
        }

        [HttpPost]
        public ActionResult AzuriranjeProfila(string korime, string lozinka, string ime, string prezime, string pol)
        {
            if (string.IsNullOrEmpty(korime)||string.IsNullOrEmpty(lozinka)||string.IsNullOrEmpty(ime)||string.IsNullOrEmpty(prezime)||string.IsNullOrEmpty(pol)){
                Session["Poruka"] = "Sva polja moraju biti popunjena.";
                return RedirectToAction("PrikazProfila");
            }
            HttpCookie cookie = Request.Cookies["Korisnik"];
            var domacin = Domacini.domacini[cookie.Value];
            Enumeracije.Pol Pol;
            if (pol == Enumeracije.Pol.MUSKO.ToString())
            {
                Pol = Enumeracije.Pol.MUSKO;
            }
            else
            {
                Pol = Enumeracije.Pol.ZENSKO;
            }

            if (domacin.KorisnickoIme != korime) //ako je menjao kor ime
            {
                if (!Administratori.aministratori.ContainsKey(korime) && !Domacini.domacini.ContainsKey(korime) && !Gosti.gosti.ContainsKey(korime)) //ako novo kor ime niko drugi vec ne koristi
                {
                    string staroIme = domacin.KorisnickoIme;
                    Domacini.domacini[staroIme].KorisnickoIme = korime;
                    Domacini.domacini[staroIme].Lozinka = lozinka;
                    Domacini.domacini[staroIme].Ime = ime;
                    Domacini.domacini[staroIme].Prezime = prezime;
                    Domacini.domacini[staroIme].Pol = Pol;
                    
                    HttpCookie DomacinCookie = new HttpCookie("Korisnik", korime);
                    HttpContext.Response.SetCookie(DomacinCookie);

                    Domacini.domacini[korime] = Domacini.domacini[staroIme];
                    Domacini.domacini.Remove(staroIme);

                    IzmeniKorisnikaTxt(Domacini.domacini[korime], "domacini.txt",staroIme);
                    Session["Poruka"] = "Podaci su promenjeni uspesno.";
                }
                else
                {
                    Session["Poruka"] = "Ovo korisnicko ime je zauzeto.";
                    
                }
            }
            else //Ako nije menjao kor ime
            {
                Domacini.domacini[domacin.KorisnickoIme].KorisnickoIme = korime; //moze bez ovoga
                Domacini.domacini[domacin.KorisnickoIme].Lozinka = lozinka;
                Domacini.domacini[domacin.KorisnickoIme].Ime = ime;
                Domacini.domacini[domacin.KorisnickoIme].Prezime = prezime;
                Domacini.domacini[domacin.KorisnickoIme].Pol = Pol;
                IzmeniKorisnikaTxt(Domacini.domacini[korime], "domacini.txt",korime);
                Session["Poruka"] = "Podaci su promenjeni uspesno.";
            }
            foreach(var apartman in Domacini.domacini[domacin.KorisnickoIme].ApartmaniZaIzdavanje.Values) //Mora se azirirati i domacin apartmana
            {
                apartman.Domacin = Domacini.domacini[domacin.KorisnickoIme];
            }
            return RedirectToAction("PrikazProfila");
        }

        
        private MultiSelectList GetSadrzaj(string[] OznaceniSadrzaj)
        {
            List<Sadrzaj> Sadrzaji = new List<Sadrzaj>();
            foreach(var sadrzaj in ApartmaniISadrzaji.Sadrzaji.Values)
            {
                if (sadrzaj.Obrisan == false)
                {
                    Sadrzaji.Add(sadrzaj);
                }
            }
            return new MultiSelectList(Sadrzaji, "ID", "Naziv", OznaceniSadrzaj);
        }

        public ActionResult DodajApartman()
        {
            ViewBag.ListaSadrzaja = GetSadrzaj(null);
            return View();
        }

        [HttpPost]
        public ActionResult DodajApartman(FormCollection form,string DatumOd,string DatumDo,string Postanski, string GeoSirina,string GeoDuzina,string TipApa, string brojSoba,string brojGostiju, string mesto, string ulica, string broj, string cena)
        {
            if (string.IsNullOrEmpty(DatumDo) || string.IsNullOrEmpty(DatumOd) || string.IsNullOrEmpty(Postanski) || string.IsNullOrEmpty(GeoDuzina) || string.IsNullOrEmpty(GeoSirina) || string.IsNullOrEmpty(TipApa) || string.IsNullOrEmpty(brojSoba) || string.IsNullOrEmpty(brojGostiju) || string.IsNullOrEmpty(mesto) || string.IsNullOrEmpty(ulica) || string.IsNullOrEmpty(broj) || string.IsNullOrEmpty(cena))
            {
                Session["PorukaDodavanje"] = "Sva polja moraju biti popunjena.";
                return RedirectToAction("DodajApartman");
            }
            Session["PorukaDodavanje"] = "";

            HttpCookie cookie = Request.Cookies["Korisnik"];
            var domacin = Domacini.domacini[cookie.Value];

            DateTime Datumod = DateTime.Parse(DatumOd);
            DateTime Datumdo = DateTime.Parse(DatumDo);

            List<DateTime> datumi = new List<DateTime>();
            DateTime datum = new DateTime(Datumod.Year, Datumod.Month, Datumod.Day);
            while (datum != Datumdo)
            {
                datumi.Add(datum);
                datum= datum.AddDays(1);
            }

            Enumeracije.TipApart tip;
            if (Enumeracije.TipApart.CEO_APART.ToString() == TipApa)
            {
                tip = Enumeracije.TipApart.CEO_APART;
            }
            else
            {
                tip = Enumeracije.TipApart.SOBA;
            }

            Apartman apartman = new Apartman(domacin, tip, int.Parse(brojSoba), int.Parse(brojGostiju), new Lokacija(GeoSirina, GeoDuzina, new Adresa(ulica, int.Parse(broj), int.Parse(Postanski), mesto)), int.Parse(cena));

            List<Slika> list = new List<Slika>();

            if (Request.Files.Count > 0)
            {
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    var file = Request.Files[i];

                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var path = Path.Combine(Server.MapPath("~/Images/"), fileName);

                        file.SaveAs(path);
                        Slika slika = new Slika(fileName, path);
                        UpisApartmanSlika(apartman.ID, slika.ID, "SlikaID_ApartmanID.txt");
                        list.Add(slika);
                        UpisSlike(slika, "slike.txt");
                    }
                }

            }
          
            if (!string.IsNullOrEmpty(form["Sadrzaji"]))
            {
                string OznaceniSadrzaj = form["Sadrzaji"];

MyFirstMVCWebApp/Views/Domacin/DodajApartman.cshtml
@{
    ViewBag.Title = "DodajApartman";
}

<head>
    <style>
        .divLogovanje {
            background: #66d1ff;
            text-align: center;
        }
        body {
            background-image: url("glavna.png");
        }
        .divAdmin {
            background: #66d1ff;
            text-align: center;
        }

        .divOdjava {
            text-align: right;
            background: #faffbf;
            font-size: 26px;
        }
        .divDodavanje {
            background: #66d1ff;
            text-align: center;
            font-weight: bold;
        }

        .divDomacin {
            background: #66d1ff;
            text-align: center;
        }
        .divtext {
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="divDomacin"> <h2>Domacin</h2></div>
    <div class="divOdjava">
        <div>
            <a href="~/Domacin/Index">Moji Apartmani</a>
            |
            <a href="~/Domacin/PrikazProfila">Moj Profil</a>
            |
            <a href="~/Home/Index">Odjavi me</a>
        </div>
    </div>
    <div class="divtext">
        <h2>Dodavanje Apartmana</h2>
    </div>
    <div class="divDodavanje">
        @using (Html.BeginForm("DodajApartman", "Domacin", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
        <table border="1" align="center">
            <tr>
                <th>Tip:</th>
                <td>
                    <select name="TipApa">
                        <option value="CEO_APART">CEO_APART</option>
                        <option value="SOBA">SOBA</option>
                    </select>
                </td>

            </tr>
            <tr>
                <th>Broj soba:</th>
                <td><input type="number" name="brojSoba" /></td>
            </tr>
            <tr>
                <th>Broj Gostiju:</th>
                <td><input type="number" name="brojGostiju" /></td>
            </tr>
            <tr>
                <th>Mesto:</th>
                <td><input type="text" name="mesto" /></td>
            </tr>
            <tr>
                <th>Ulica i broj</th>
                <td><input type="text" name="ulica" />|<input type="number" name="broj" /></td>
            </tr>
            <tr>
                <th>Geografska sirina:</th>
                <td><input type="number" name="GeoSirina" /></td>
            </tr>
            <tr>
                <th>Geografska duzina:</th>
                <td><input type="number" name="GeoDuzina" /></td>
            </tr>
            <tr>
                <th>Postanski broj:</th>
                <td><input type="number" name="Postanski" /></td>
            </tr>
            <tr>
                <th>Cena:</th>
                <td><input type="number" name="cena" /></td>
            </tr>
            <tr>
                <th>Datum od kog se izdaje:</th>
                <td><input type="date" name="DatumOd" /></td>
            </tr>
            <tr>
                <th>Datum do kog se izdaje:</th>
                <td><input type="date" name="DatumDo" /></td>
            </tr>
            <tr>
                <th>Sadrzaji apartmana:</th>
                <td>
                    @using (Html.BeginForm())
                    {

                        <div class="editor-field">

                            @Html.ListBox("Sadrzaji", ViewBag.ListaSadrzaja as MultiSelectList)

                        </div>

                    }
                </td>
            </tr>
            <tr>
                <th>Dodaj Slike:</th>
                <td>
                    <input type="file" name="file" multiple="multiple" />
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <input type="submit" id="Submit" value="Dodaj" />
                </td>
            </tr>
        </table>
        }
        <h3>@Session["PorukaDodavanje"]</h3>
    </div>
</body>

MyFirstMVCWebApp/Views/Domacin/Index.cshtml
@model List<Apartman>

@{
    ViewBag.Title = "Index";
}
<head>
    <style>
        .divOdjava {
            text-align: right;
            background: #faffbf;
            font-size: 26px;
        }
        body {
            background-image: url("glavna.png");
        }
        .divDodajApartman {
            text-align: left;
            background: #faffbf;
            font-size: 26px;
        }

        .divTabela {
            text-align: center;
            background: #c4ff66;
            font-weight: bold;
        }

        .divPretraga {
            background: #f7f783;
            text-align: center;
        }

        .divDomacin {
            background: #66d1ff;
            text-align: center;
        }
    </style>
</head>

<body>

    <div class="divDomacin"> <h2>Domacin</h2></div>
    <div class="divOdjava">
        <div>
            <a href="~/Domacin/Index">Moji Apartmani</a>
            |
            <a href="~/Domacin/PrikazProfila">Moj Profil</a>
            |
            <a href="~/Home/Index">Odjavi me</a>
        </div>
    </div>
    <div class="divDodajApartman">
        <h2><a href="~/Domacin/DodajApartman">Dodaj Novi Apartman</a></h2>
    </div>


    <div class="divPretraga">

        <div>
            <form action="~/Domacin/Index">
                <table align="center">
                    <tr><th>Grad:</th><th>Cena od:</th><th>Cena do:</th><th>Broj soba:</th><th>broj osoba:</th></tr>
                    <tr>
                        <td><input type="text" name="Grad" /> | </td>
                        <td><input type="number" name="CenaOd" /> | </td>
                        <td><input type="number" name="CenaDo" />|</td>
                        <td><input type="number" name="BrojSoba" />|</td>
                        <th><input type="number" name="BrojOsoba" />|</th>
                        <td rowspan="2"><input type="submit" name="dugme" value="Pretrazi" /></td>
                    </tr>

                </table>
            </form>
        </div>
        <div>
            <form action="~/Domacin/Index" method="post">
                <table align="center">
                    <tr>
                        <th>Tip:</th>
                        <th>Status:</th>
                        <th>Sadrzaji apartmana</th>

                    </tr>
                    <tr>
                        <td>
                            <select name="TIP">
                                <option value="SVI">Svi Tipovi</option>
                                <option value="CEO_APART">CEO_APART</option>
                                <option value="SOBA">SOBA</option>
                            </select>|
                        </td>
                        <td>
                            <select name="STATUS">
                                <option value="SVI">NEAKTIVNI I AKTIVNI </option>
                                <option value="NEAKTIVAN">NEAKTIVAN </option>
                                <option value="AKTIVAN">AKTIVAN</option>

                            </select>|
                        </td>
                        <td>
                            @using (Html.BeginForm())
                            {

                                <div>

                                    @Html.ListBox("Sadrzaji", ViewBag.ListaSadrzaja as MultiSelectList)

                                </div>

                            }
                        </td>
                        <td rowspan="2">
                            <input name="dugme" type="submit" value="Primeni filter" />
                        </td>
                    </tr>
                </table>
            </form>
            <div>
                <form action="~/Domacin/Index">
                    <select name="SORTIRANJE">
                        <option value="opadajuce">Cena opadajuce</option>
                        <option value="rastuce">Cena Rascuce</option>
                    </select>
                    <input name="dugme" type="submit" value="sortiraj" />
                </form>
            </div>
        </div>
    </div>
    <div class="divTabela">
        @if (Model.Count == 0)
        {
            <h3>Nema trazenih apartmana</h3>
        }
        else
        {
            <table border=5 BORDERCOLOR=#21b319 align="center">
                <tr>
                    <th>Tip Apartmana:</th>
                    <th>Broj Soba:</th>
                    <th>Broj Gostiju:</th>
                    <th>Lokacija:</th>
                    <td>Sadrzaj Apartmana:</td>
                    <th>Cena:</th>
                    <th>Slike:</th>
                    <th>Status:</th>
                    <th>Komentari:</th>
                    <th>Modifikacija</th>
                    <th>Brisanje</th>

                </tr>

                @foreach (var a in Model)
                {
                    <form action="~/Domacin/IzmeniIzbrisi" method="post" >
                        <tr>
                            <td>@a.TipApartmana.ToString()</td>
                            <td>@a.BrojSoba</td>
                            <td>@a.BrojGostiju</td>
                            <td>@a.Lokacija.Adresa.ToString()</td>
                            <td>
                                @foreach (var sadrzaj in a.SadrzajApartmana)
                                {
                                    if (sadrzaj.Obrisan == false)
                                    {
                                        @sadrzaj.Naziv <p />
                                    }

                                }
                            </td>
                            <td>@a.Cena</td>
                            <td>
                                @foreach (var slika in a.Slike)
                                {
                                    <img src="~/Images/@slika.naziv" height="70" width="90" />
                                }
                            </td>
                            <td>
                                @a.StatusApartmana.ToString()
                            </td>
                            <td>
                                @foreach (var komentar in a.Komentari)
                                {
                                    @komentar.TakstKomentara;
                                    @(",  Ocena:" + komentar.Ocena);
                                    <br />
                                }
                            </td>
                            <td>
                                <input type="hidden" name="id" value="@a.ID" />
                                <input type="submit" name="izmena" value="Modifikuj" />
                            </td>
                            <td>
                                <input type="hidden" name="id" value="@a.ID" />
                                <input type="submit" neme="izmena" value="Obrisi" />
                            </td>
                        </tr>
                    </form>
                }
            </table>
        }
    </div>
</body>

MyFirstMVCWebApp/Views/Domacin/IzmeniIzbrisi.cshtml
@model Apartman
@{
    ViewBag.Title = "IzmeniIzbrisi";
}

<head>
    <style>

        .divDodavanje {
            background: #66d1ff;
            text-align: center;
            font-weight: bold;
        }
        body {
            background-image: url("glavna.png");
        }

        .divOdjava {
            text-align: right;
            background: #faffbf;
            font-size: 26px;
        }

        .divtext {
            text-align: center;
        }
        .divDomacin {
            background: #66d1ff;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="divDomacin"> <h2>Domacin</h2></div>
    <div class="divOdjava">
        <div>
            <a href="~/Domacin/Index">Moji Apartmani</a>
            |
            <a href="~/Domacin/PrikazProfila">Moj Profil</a>
            |
            <a href="~/Home/Index">Odjavi me</a>
        </div>
    </div>
    <div class="divtext">
        <h2>Izmena Apartmana</h2>
    </div>
    <div class="divDodavanje">
        @using (Html.BeginForm("IzmenaApartmana", "Domacin", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <table border="1" align="center">

                <tr>
                    <th>Tip:</th>
                    <td>
                        <select name="TipApa">
                            @if (Model.TipApartmana.ToString() == "CEO_APART")
                            {
                                <option value="CEO_APART">CEO_APART</option>
                                <option value="SOBA">SOBA</option>
                            }
                            else
                            {
                                <option value="SOBA">SOBA</option>
                                <option value="CEO_APART">CEO_APART</option>
                            }
                        </select>
                    </td>

                </tr>
                <tr>
                    <th>Broj soba</th>
                    <td><input type="number" name="brojSoba" value="@Model.BrojSoba" /></td>
                </tr>
                <tr>
                    <th>Broj Gostiju</th>
                    <td><input type="number" name="brojGostiju" value="@Model.BrojGostiju" /></td>
                </tr>
                <tr>
                    <th>Mesto</th>
                    <td><input type="text" name="mesto" value="@Model.Lokacija.Adresa.NaseljenoMesto" /></td>
                </tr>
                <tr>
                    <th>Ulica i broj</th>
                    <td><input type="text" name="ulica" value="@Model.Lokacija.Adresa.Ulica" />|<input type="number" name="broj" value="@Model.Lokacija.Adresa.Broj" /></td>
                </tr>
                <tr>
                    <th>Geografska sirina:</th>
                    <td><input type="number" name="GeoSirina" value="@Model.Lokacija.GeoSirina" /></td>
                </tr>
                <tr>
                    <th>Geografska duzina:</th>
                    <td><input type="number" name="GeoDuzina" value="@Model.Lokacija.GeoSirina" /></td>
                </tr>
                <tr>
                    <th>Postanski broj:</th>
                    <td><input type="number" name="Postanski" value="@Model.Lokacija.Adresa.PostanskiBroj" /></td>
                </tr>
                <tr>
                    <th>Cena</th>
                    <td><input type="number" name="cena" value="@Model.Cena" /></td>
                </tr>
                <tr>
                    <th>Sadrzaji apartmana</th>
                    <td>
                        @using (Html.BeginForm())
                        {

                            <div class="editor-field">

                                @Html.ListBox("Sadrzaji", ViewBag.ListaSadrzaja as MultiSelectList)

                            </div>

                        }
                    </td>
                </tr>
                <tr>
                    <th>Zameni stare slike:</th>
                    <td>
                        <input type="file" name="file" multiple="multiple" />
                    </td>
                </tr>
                
                <tr>
                    <td colspan="2">
                        <input type="hidden" name="ID" value="@Model.ID" />
                        <input type="submit" value="Izmeni" />
                    </td>
                </tr>

            </table>
        }
    </div>
</body>

MyFirstMVCWebApp/Views/Domacin/PrikazProfila.cshtml
@model Domacin
@{
    ViewBag.Title = "PrikazProfila";
}

<head>
    <style>
        .divLogovanje {
            background: #66d1ff;
            text-align: center;
        }
        body {
            background-image: url("glavna.png");
        }
        .divAdmin {
            background: #66d1ff;
            text-align: center;
        }

        .divOdjava {
            text-align: right;
            background: #faffbf;
            font-size: 26px;
        }
        .divDomacin {
            background: #66d1ff;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="divDomacin"> <h2>Domacin</h2></div>
    <div class="divAdmin">
        <h2>Profil korisnika: @Model.Ime @Model.Prezime</h2>
    </div>
    <div class="divOdjava">
        <div>
            <a href="~/Domacin/Index">Moji Apartmani</a>
            |
            <a href="~/Domacin/PrikazProfila">Moj Profil</a>
            |
            <a href="~/Home/Index">Odjavi me</a>
        </div>

    </div>
    <div class="divLogovanje">
        <form action="~/Domacin/AzuriranjeProfila" method="post">
            <table border="1" align="center" width="200">

                <tr>
                    <th>Korisnicko ime:</th>
                    <td><input type="text" name="korime" value="@Model.KorisnickoIme" /></td>

                </tr>
                <tr>
                    <th>Lozinka:</th>
                    <td><input type="text" name="lozinka" value="@Model.Lozinka" /></td>

                </tr>
                <tr>
                    <th>Ime:</th>
                    <td><input type="text" name="ime" value="@Model.Ime" /></td>

                </tr>
                <tr>
                    <th>Prezime:</th>
                    <td><input type="text" name="prezime" value="@Model.Prezime" /></td>
                </tr>
                <tr>
                    <th>Pol:</th>
                    <td>
                        <select name="pol">
                            @if (Model.Pol.ToString() == "MUSKO")
                            {
                                <option value="MUSKO">MUSKO</option>
                                <option value="ZENSKO">ZENSKO</option>
                            }
                            else
                            {
                                <option value="ZENSKO">ZENSKO</option>
                                <option value="MUSKO">MUSKO</option>
                            }

                        </select>

                    </td>

                </tr>
                <tr>
                    <td colspan="2"><input type="submit" value="IZMENI" /></td>
                </tr>

            </table>
        </form>
    </div>
    <div>
        <h2>@Session["Poruka"]</h2>
    </div>
</body>